<a href="https://colab.research.google.com/github/rochmanofenna/Neural_Networks/blob/main/reshape_slice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#Reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#if we don't know number of items, reshape using -1
#row x column, row % num elements == 0
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

#remember there is difference between shape vs view

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
my_torch2[1] = 4141
my_torch2

tensor([[   0,    1,    2,    3,    4],
        [4141, 4141, 4141, 4141, 4141]])

In [13]:
my_torch3 = torch.arange(10)
my_torch3

my_torch4 = my_torch3.reshape(5,2)
my_torch4

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [15]:
my_torch4[:,1]

tensor([1, 3, 5, 7, 9])

In [14]:
my_torch4[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])