<a href="https://colab.research.google.com/github/rochmanofenna/Neural_Networks/blob/main/tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [13]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])
tensor_a + tensor_b
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [6]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [7]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [8]:
torch.mul(tensor_a, tensor_b)


tensor([ 5, 12, 21, 32])

In [9]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [10]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [12]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [17]:
#Reassignment
# tensor_a = tensor_a + tensor_b
#or
tensor_a.add_(tensor_b)

tensor([26, 32, 38, 44])